### ISSUE TITLE
Waiting time should be string

### ISSUE THREAD

**Issue by sschleic** [Buxdehuda/strato-certbot#17]
Hey there,

thanks for your work publishing this repo. Its wirking great for me :).

Could you please adapt the manaul as well as the json.sample to indicate that the value of waiting_time should be of type string?
Currently the config.json shows type int which leads to a python error, since isdigit() is only defined for type string and not for integer.

Thank you,
Merry xmas and an happy new year
Stephan

**Comment by Buxdehuda** [comment]
Hi,
thanks for letting me know.
It seems kind of counterproductive to me to require the time as a string, so I removed the parsing part.
The script should now work by having just a number the json as python converts the type automatically.

Please pull the latest version and see if it works for you.

**Comment by sschleic** [comment]
Fine from my side.
