### ISSUE TITLE
ERROR: Domain DOMAIN.de not found in strato packages     

### ISSUE THREAD

**Issue by Jannomag** [Buxdehuda/strato-certbot#19]
Hi,
I get the error in the title when I try your scripts.
Here’s the full log:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log                                                               
Plugins selected: Authenticator manual, Installer None                                                                 
Cert is due for renewal, auto-renewing...                                                                              
Renewing an existing certificate                                                                                       
Performing the following challenges:                                                                                   
dns-01 challenge for DOMAIN.de                                                                                       
dns-01 challenge for DOMAIN.de                                                                                       
Running manual-auth-hook command: /home/jan/scripts/strato-certbot/auth-hook.py                                        
Output from manual-auth-hook command auth-hook.py:                                                                     
INFO: txt_key: _acme-challenge                                                                                         
INFO: txt_value: REMOVED                                                           
INFO: second_level_domain_name: DOMAIN.de                                                                            
INFO: domain_name: DOMAIN.de                                                                                         
INFO: 2FA is not used.                                                                                                 
DEBUG: session_id: REMOVED                                                                      
ERROR: Domain DOMAIN.de not found in strato packages                                                                 
                                                                                                                       
manual-auth-hook command "/home/jan/scripts/strato-certbot/auth-hook.py" returned error code 1                         
Running manual-auth-hook command: /home/jan/scripts/strato-certbot/auth-hook.py                                        
Output from manual-auth-hook command auth-hook.py:                                                                     
INFO: txt_key: _acme-challenge                                                                                         
INFO: txt_value: REMOVED                                                           
INFO: second_level_domain_name: DOMAIN.de                                                                            
INFO: domain_name: DOMAIN.de                                                                                         
INFO: 2FA is not used.                                                                                                 
DEBUG: session_id: REMOVED                                                                      
ERROR: Domain DOMAIN.de not found in strato packages                                                                 
                                                                                                                       
manual-auth-hook command "/home/jan/scripts/strato-certbot/auth-hook.py" returned error code 1                         
Waiting for verification...                                                                                            
Challenge failed for domain DOMAIN.de                                                                                
Challenge failed for domain DOMAIN.de                                                                                
dns-01 challenge for DOMAIN.de                                                                                       
dns-01 challenge for DOMAIN.de                                                                                       
Cleaning up challenges                                                                                                 
Running manual-cleanup-hook command: /home/jan/scripts/strato-certbot/cleanup-hook.py                                  
Output from manual-cleanup-hook command cleanup-hook.py:
Output from manual-cleanup-hook command cleanup-hook.py:                                                               
INFO: txt_key: _acme-challenge                                                                                         
INFO: txt_value: REMOVED
INFO: second_level_domain_name: DOMAIN.de
INFO: domain_name: DOMAIN.de
INFO: 2FA is not used.
DEBUG: session_id: REMOVED
ERROR: Domain DOMAIN.de not found in strato packages

manual-cleanup-hook command "/home/jan/scripts/strato-certbot/cleanup-hook.py" returned error code 1
Running manual-cleanup-hook command: /home/jan/scripts/strato-certbot/cleanup-hook.py
Output from manual-cleanup-hook command cleanup-hook.py:
INFO: txt_key: _acme-challenge
INFO: txt_value: REMOVED
INFO: second_level_domain_name: DOMAIN.de
INFO: domain_name: DOMAIN.de
INFO: 2FA is not used.
DEBUG: session_id: REMOVED
ERROR: Domain DOMAIN.de not found in strato packages

manual-cleanup-hook command "/home/jan/scripts/strato-certbot/cleanup-hook.py" returned error code 1
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: DOMAIN.de
   Type:   unauthorized
   Detail: No TXT record found at _acme-challenge.DOMAIN.de

   Domain: DOMAIN.de
   Type:   unauthorized
   Detail: No TXT record found at _acme-challenge.DOMAIN.de

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

```

And this is the command I executed:

```
certbot certonly --manual --preferred-challenges dns --manual-public-ip-logging-ok --manual-auth-hook /home/jan/scripts/strato-certbot/auth-hook.py --manual-cleanup-hook /home/jan/scripts/strato-certbot/cleanup-hook.py -d DOMAIN.de -d *.DOMAIN.de --dry-run 

```

It worked a few months ago but not for two domains (wildcard). But after you fixed issue #14 I wanted to try it again.

And yes, the domain is present on strato.de.

any ideas?

**Comment by Jannomag** [comment]
Using commit b8aba15 works

**Comment by Buxdehuda** [comment]
@hvoss It seems your new regex from #18 does not work for everyone. Could you look into that?

**Comment by daniel-lerch** [comment]
The new regex from #18 only works if you manually set the name of your package like the domain you want to obtain a certificate for. I would prefer to have an algorithm that searches for the domain in all packages instead of searching for a package name.

**Comment by Buxdehuda** [comment]
I changed the regex back to the previous one and used @hvoss 's regex as a fallback just in case.

Let me know if this works for you @daniel-lerch @Jannomag

**Comment by hvoss** [comment]
Hi,

I can confirm the issue. 

Also I wrote a little test script (sry for my bad python skills): 
https://github.com/hvoss/strato-certbot/blob/feature/testProjectId/test/get_package_id_test.py

Furthermore I added a new pattern to the test file. Please check if this one working for you.

Cheers
Henrik

Output of the script:
```
A new pattern:
check domain-a.de is in project 7: True
check domain-b.de is in project 6: True
check domain-c.de is in project 5: True
check domain-d.de is in project 4: True
check domain-e.de is in project 2: True
check domain-f.de is in project 2: True
check domain-g.de is in project 1: True

My bad pattern
check domain-a.de is in project 7: True
check domain-b.de is in project 6: True
check domain-c.de is in project 5: True
check domain-d.de is in project 4: True
check domain-e.de is in project 2: False
check domain-f.de is in project 2: False
check domain-g.de is in project 1: True

Actual pattern:
check domain-a.de is in project 7: True
check domain-b.de is in project 6: False
check domain-c.de is in project 5: False
check domain-d.de is in project 4: False
check domain-e.de is in project 2: False
check domain-f.de is in project 2: False
check domain-g.de is in project 1: False
```

**Comment by Buxdehuda** [comment]
> Hi,
> 
> I can confirm the issue.
> 
> Also I wrote a little test script (sry for my bad python skills): https://github.com/hvoss/strato-certbot/blob/feature/testProjectId/test/get_package_id_test.py
> 
> Furthermore I added a new pattern to the test file. Please check if this one working for you.
> 
> Cheers Henrik
> 
> Output of the script:
> 
> ```
> A new pattern:
> check domain-a.de is in project 7: True
> check domain-b.de is in project 6: True
> check domain-c.de is in project 5: True
> check domain-d.de is in project 4: True
> check domain-e.de is in project 2: True
> check domain-f.de is in project 2: True
> check domain-g.de is in project 1: True
> 
> My bad pattern
> check domain-a.de is in project 7: True
> check domain-b.de is in project 6: True
> check domain-c.de is in project 5: True
> check domain-d.de is in project 4: True
> check domain-e.de is in project 2: False
> check domain-f.de is in project 2: False
> check domain-g.de is in project 1: True
> 
> Actual pattern:
> check domain-a.de is in project 7: True
> check domain-b.de is in project 6: False
> check domain-c.de is in project 5: False
> check domain-d.de is in project 4: False
> check domain-e.de is in project 2: False
> check domain-f.de is in project 2: False
> check domain-g.de is in project 1: False
> ```

Thank you. Unfortunately your new regex only matches cID=7.
However thanks to your html file I was able to create a new regex that passes all tests.

@everyone
If there are still problems with the newest version, feel free to send me your html files.

**Comment by hvoss** [comment]
Maybe someone can add unit testing framework and then we can add some automated tests?

**Comment by Buxdehuda** [comment]
> Maybe someone can add unit testing framework and then we can add some automated tests?

👍 Just did that.

**Comment by kernelport** [comment]
I have to fake the get_package_id return value to "1" and it works for all domains 

diff --git a/certbotstratoapi.py b/certbotstratoapi.py
index cc999b0..1ca4b2a 100644
--- a/certbotstratoapi.py
+++ b/certbotstratoapi.py
@@ -150,6 +150,10 @@ class CertbotStratoApi:
             request.text.replace('\n', ' ')
             )
 
+
+        self.package_id = 1 #result.group('cID')
+        return
+
         if result is None:
             print(f'ERROR: Domain {self.second_level_domain_name} not '
                 'found in strato packages')

Also I have to set the STRATO SPF-Rule to "v=spf1  redirect=_spf.strato.com" (with two space between spf1 and redirect) to prevent overwriting the "Standard STRATO Mailserver" rule

**Comment by Buxdehuda** [comment]
> I have to fake the get_package_id return value to "1" and it works for all domains

1 is the default ID if you have only bought one package. If you have multiple, there will be different values. (see #5)
I don't know why it doesn't match an ID for you, you'd have to send me the html for that.

> Also I have to set the STRATO SPF-Rule to "v=spf1 redirect=_spf.strato.com" (with two space between spf1 and redirect) to prevent overwriting the "Standard STRATO Mailserver" rule

I'm not sure what you mean with that. Do you mean the spf_type parameter in line 237?

**Comment by daniel-lerch** [comment]
The regex in the current commit 6950a3d5181eb015cad32bd72dbd70d0e22fc64a is wrong. It doesn't match any domain for me because it does not respect the space as sent by Strato. The following Regex works for me:

```diff
diff --git a/certbotstratoapi.py b/certbotstratoapi.py
index cc999b0..866c6ed 100644
--- a/certbotstratoapi.py
+++ b/certbotstratoapi.py
@@ -144,7 +144,7 @@ class CertbotStratoApi:
             'node': 'kds_CustomerEntryPage',
         })
         result = re.search(
-            r'<div class="package-information"> <span\s+class="domains_\d+_long">.+?'
+            r'<div class="package-information">\s+<span\s+class="domains_\d+_long">.+?'
             + self.second_level_domain_name.replace('.', r'\.')
             + r'.+?cID=(?P<cID>\d+)',
             request.text.replace('\n', ' ')
```

I don't know much about Python libraries but as performance is not really a concern for this application, it would seem easier to me to use a DOM parser and get the correct element via CSS selector as:
```javascript
for (const element of document.querySelectorAll('div.package-information span') {
    if (element.innerHtml.match(/* some very simple regex */)
}
```

A similar implementation in Python would make the implementation more robust and easier to understand and maintain than complex regular expressions.

**Comment by Buxdehuda** [comment]
Thanks for the info, I updated it accordingly.

I'm not sure how easy it would be to parse the correct values with a html parser, but if you want to give it a go, I'm open for a pull request.

**Comment by fritzfranzke** [comment]
I am getting the same error by certbot: `ERROR: Domain my.domain not found in strato packages`  
But also, in the summary at the end it claims
```
Domain: my.domain
Type:   unauthorized
Detail: No TXT record found at _acme-challenge.my.domain
```

Any ideas?

**Comment by Buxdehuda** [comment]
Hi, I added a fallback value for the package ID which should cover most cases.

If you still have problems you probably have multiple packages with strato. In this case please post your HTML code (you can censor the sessionId and domain names), so that the parsing logic can be changed

**Comment by fritzfranzke** [comment]
Works like a charm, thanks for the quick fix/reply! 👌

For reference, I am also a customer of the Strato HiDrive package, maybe that's the culprit. Though I have had this for quite some time so I don't quite know why this has only now started to become a problem.

**Comment by chrstn-hntschl** [comment]
Hi, it seems to me as if strato changed the html code. For me this looks like this as of today:
```
...
<div id="package_information_ID" class="package-information">
                                            <p> domain_a.de </p>
                                            <p> domain_b.de </p>
...
```
While your fallback also works for me, it might be better to fix the regex? I tried to get my head around your code but failed miserably ...

**Comment by Buxdehuda** [comment]
The script now checks for the new html.
Replaced the regex parsing with beautifulsoup because it is more readable.

2FA and TXT record parsing is still done with regex because I could not decipher the existing regex and have not test data available for these pages.
