### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by alpharesearch** [Buxdehuda/strato-certbot#2]
I guess this script doesn't work anymore because the web page uses a captcha now? Or is there a workaround or way to disable the captcha?

Thanks,
Markus

**Comment by Buxdehuda** [comment]
I'm currently using another provider so I can't tell, but I guess if there is a captcha, it won't be possible to automate this anymore.

**Comment by Buxdehuda** [comment]
It seems that this script works for other people at the moment, so I'll close this issue.
