### ISSUE TITLE
plugin seems not to work anymore.

### ISSUE THREAD

**Issue by smartheit** [Buxdehuda/strato-certbot#22]
I used the strato certbot plugin since a year or so.
On Monday all my txt records on the strato server were gone (cron job every Sunday at midnight). I thought Strato changes something and deleted my TXT records.

It turns out that the plugin deletes all TXT records.

dns-01 challenge for example.co
Cleaning up challenges
Running manual-cleanup-hook command: /usr/local/bin/strato-certbot/cleanup-hook.py
Output from manual-cleanup-hook command cleanup-hook.py:
INFO: txt_key: _acme-challenge
INFO: txt_value: JxCrxYdEUK84FRx0PV34bSXC3ZJhqK5ys
INFO: second_level_domain_name: example.co
INFO: domain_name: example.co
INFO: 2FA is not used.
DEBUG: session_id: 964e99252b2ef3e0dd8227ff341cca
INFO: strato package id (cID): 2
INFO: Current cname/txt records:
INFO: New cname/txt records:

Some challenges have failed.

After calling
`certbot certonly --force-renew --manual --preferred-challenges dns --manual-auth-hook $(pwd)/auth-hook.py --manual-cleanup-hook $(pwd)/cleanup-hook.py --domain example.co --domain *.example.co`
 all TXT records are gone.

**Comment by chrstn-hntschl** [comment]
Can confirm - happened to me as well. Same error message, same result on subdomains. I also thought at first to blame Strato.

**Comment by Buxdehuda** [comment]
I guess Strato changed their site so the records are not read correctly anymore.
Just paste the new HTML, we can probably figure something out.

**Comment by Buxdehuda** [comment]
Closed via #23
