### ISSUE TITLE
Strato login not accepted

### ISSUE THREAD

**Issue by jonathanwerle** [Buxdehuda/strato-certbot#24]
Hi,
thanks for your work on this amazing script! Unfortunately, I can't get it running. Thanks in advance for your help!

```bash
user@host:~/strato-certbot$ sudo certbot certonly --manual --preferred-challenges dns --manual-auth-hook $(pwd)/auth-hook.py --manual-cleanup-hook $(pwd)/cleanup-hook.py -d *.example.com -d example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
An RSA certificate named example.com already exists. Do you want to update its key
type to ECDSA?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(U)pdate key type/(K)eep existing key type: K
Renewing an existing certificate for *.example.com and example.com
Hook '--manual-auth-hook' for example.com reported error code 1
Hook '--manual-auth-hook' for example.com ran with output:
 INFO: txt_key: _acme-challenge
 INFO: txt_value: REDACTED
 INFO: second_level_domain_name: example.com
 INFO: domain_name: example.com
 INFO: 2FA is not used.
 ERROR: Strato login not accepted.
Hook '--manual-auth-hook' for example.com reported error code 1
Hook '--manual-auth-hook' for example.com ran with output:
 INFO: txt_key: _acme-challenge
 INFO: txt_value: REDACTED
 INFO: second_level_domain_name: example.com
 INFO: domain_name: example.com
 INFO: 2FA is not used.
 ERROR: Strato login not accepted.
```

This is my redacted `strato-auth.json`:

```json
{
    "username": "example",
    "password": "topsecretpasswordwithsomespecialcharacters",
    "totp_secret": "IWONTTELLYOU",
    "totp_devicename": "example-iphone",
    "waiting_time": 10
}
```

Why is the error "ERROR: Strato login not accepted." thrown? Or why does it say "INFO: 2FA is not used." although I have 2FA enabled?

**Comment by Buxdehuda** [comment]
The script checks if 2fa is used, depending on the response from strato after the login.
Try logging in normally with your browser and use the "inspect element" tool to check if this header tag is sent:
https://github.com/Buxdehuda/strato-certbot/blob/d5ed0c232990320224a2267389702b1849a18ae2/certbotstratoapi.py#L54

**Comment by florie1706** [comment]
I have the same issue. Using Firefox to log in and inspect the 2FA site, I would confirm that the header tag is there.

**Comment by Buxdehuda** [comment]
Hm, sorry to hear that, but that's about as far as I can help from an outside perspective. If someone wants to look into this, just open a PR

**Comment by jonathanwerle** [comment]
@Buxdehuda thanks for your fast reply! Here's a snippet from the source code. It looks like **there's a space before and after** the "Zwei-Faktor-Authentifizierung". Maybe your code can be updated to check if the code contains a h1 tag which contains "Zwei-Faktor-Authentifizierung" (a small difference in logic)? 

<img width="546" alt="image" src="https://user-images.githubusercontent.com/18647622/226195008-cd9170da-3a47-42e2-b1a6-e58da9b7342e.png">

**Comment by Buxdehuda** [comment]
Whitespaces are now ignored for this particular check. Try again and see if it works.

**Comment by florie1706** [comment]
Sorry for the late response, but it is working again. Thank you very much 👍
