### ISSUE TITLE
ERROR: Strato login not accepted.

### ISSUE THREAD

**Issue by mrcljust** [Buxdehuda/strato-certbot#28]
Hi, when running the script manually using the command in your [README](https://github.com/Buxdehuda/strato-certbot#get-certificate), I get the following output:

> Hook '--manual-cleanup-hook' for xxx.de reported error code 1
> Hook '--manual-cleanup-hook' for xxx.de ran with output:
>  INFO: txt_key: _acme-challenge
>  INFO: txt_value: xxx
>  INFO: second_level_domain_name: xxx.de
>  INFO: domain_name: xxx.de
>  INFO: 2FA is not used.
>  ERROR: Strato login not accepted.

At first I tried having Strato 2FA disabled (without totp properties in the strato-auth.json file) and got this output. Then I enabled Strato 2FA and put the two properties into the strato-auth.json file (obviously containing the current totp secret), but I am still getting the same output (and it still says "2FA is not used").

strato-auth.json content:
`{
  "api_url": "https://www.strato.de/apps/CustomerService",
  "username": "xxx",
  "password": "xxx",
  "totp_secret": "xxx",
  "totp_devicename": "authy",
  "waiting_time": 5
}`

Do you have any idea how I can fix this?

Thank you!

**Comment by Buxdehuda** [comment]
This seems similar to #26 
Try using your account number as the username in the json config

**Comment by mrcljust** [comment]
Still does not work
I just debugged (added "print(response.text)" to line 58 of certbotstratoapi.py, and got the following response:
STRATO - Access denied
For security reasons, we are unable to grant access from your network to this site.

Using a Ubuntu VPS hosted by Contabo

Do you know how I could bypass this? ^^ ty!

**Comment by Buxdehuda** [comment]
Well, if you're IP blocked, you could use a VPN, although it would be a janky solution.
It seems more sensible to just use the default HTTP acme challenge. Or even using another Nameserver with a real API

**Comment by mrcljust** [comment]
For now I put the acme text record manually and will renew it manually. Thank you anyway.

**Comment by HerrmannMax** [comment]
Greetings,
I got the same problem here
print(response.text)  in line 58
`         <div style="padding-bottom: 30px" lang="en">
             <span style="font-size: 14px; color: #777; font-weight: bold;">English</span>
             <br>
             For security reasons, we are unable to grant access from your network to this site.
         </div>
`

I dont think this has something Todo with the code.
Maybe they just have a IP Whitelist from where they allow logins

In my case I have segmented Networks and my server is in a 10.0.1.0/24 net
I guess this can be the Problem
