### ISSUE TITLE
stratobot:latest not found

### ISSUE THREAD

**Issue by hlarc** [Buxdehuda/strato-certbot#33]
While running the run.sh
It threw the following error Message
Script Unable to find image 'stratobot:latest' locally
docker: Error response from daemon: pull access denied for stratobot, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

If It helps but I dont think so:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
Kernel: 5.15.0-101-generic

**Comment by passioneight** [comment]
Did you execute the `build.sh` first? :-)

**Comment by Buxdehuda** [comment]
Seems like there was an option missing in the docker build script. Please pull the latest version and try again

**Comment by passioneight** [comment]
@Buxdehuda not sure if this is related: https://github.com/Buxdehuda/strato-certbot/issues/34 :-)

**Comment by Buxdehuda** [comment]
Honestly I'm not sure about the use case for the docker container here, all you get is the volume with the certificates.
If you want the real certbot experience with automation for webservers, just use the natively installed certbot with this script

**Comment by Buxdehuda** [comment]
This issue seems solved. If you have further problems open a new issue
