### ISSUE TITLE
Dockerfile not found when executing build.sh

### ISSUE THREAD

**Issue by passioneight** [Buxdehuda/strato-certbot#34]
## Expected
When cloning the repository, `cd`-ing into the project's root directory and executing the `./docker/build.sh` should build the `certbot` container.

## Actual
An error message is issued:

```cli
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat <omitted-absolute-path>/strato-certbot/Dockerfile: no such file or directory
```

## Steps to reproduce
1. Execute `git clone https://github.com/Buxdehuda/strato-certbot.git strato-certbot`
2. Execute `cd strato-certbot`
3. Execute `./docker/build.sh`

**Comment by Buxdehuda** [comment]
The steps should be
git clone
cd strato-certbot/docker
./build.sh

**Comment by passioneight** [comment]
@Buxdehuda thanks for clarifying :-)
Unfortunately, this results in the following error:

```cli
Sending build context to Docker daemon  157.2kB
Step 1/9 : FROM python:3-alpine as test
 ---> 723c4f8c3f62
Step 2/9 : Add ../ ./
ADD failed: forbidden path outside the build context: ../ ()
```

The Docker docs suggest that referencing a parent directory in the `ADD` command is not permitted, unless you specify the build-context correspondingly. As far as I can tell, that's what you did in the `build.sh` file. So, I'm not sure why it wouldn't allow accessing the parent folder - any idea? :-)

**Comment by Buxdehuda** [comment]
It seems the ADD step uses a path relative to the context, in which case the .. for the parent directory is not necessary. 
Try again with the latest version

**Comment by passioneight** [comment]
That checks out, thank you ❤️
