### ISSUE TITLE
Question about --manual flag

### ISSUE THREAD

**Issue by m1raculix** [Buxdehuda/strato-certbot#38]
Hi,
why do you use the `--manual` flag here?

Isn't aim of this hook to automatically generate DNS-Challenges so one can generate certs automatically? 

Manual means for me that I have to manually login at Strato and put the TXT entry into my Domain configuration.

**Comment by Buxdehuda** [comment]
Manual just means that certbot will use the auth-hook and cleanup-hook specified in the command.
The TXT records will be automatically created when you run the script for the first time and when renewing certificates in the cronjob.
